id: D442E1C55
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-04-18T11:11:31+00:00'
last_modified: '2022-05-26T08:16:13.135874+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    a1cf:
      image_group_id: I1PD95859
      title: དཔལ་མགོན་པོའི་ནང་སྒྲུབ།
      total_pages: 1856
      order: 14
      base_file: a1cf.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
