id: P45852DD8
initial_creation_type: ocr
source_metadata:
  volumes:
    70b6b91d241c46c5a13f04ae8c7f56d5:
      base_file: v014.txt
      image_group_id: I1PD95859
      title: དཔལ་མགོན་པོའི་ནང་སྒྲུབ།
      total_pages: 1856
      volume_number: 14
